openapi: 3.1.0
info:
  title: Java API MVC, JPA and Hibernate Part 1 Workshop - Core Criteria
  description: Core Criteria for Java API JPA Hibernate Workshop
  version: 0.2.4
  contact:
    name: MVC, Java and Hibernate Workshop

servers:
  - url: http://localhost:4000
tags:
  - name: teachers
paths:
  /teachers:
    post:
      tags:
        - teachers
      summary: Create a new teacher
      description: Create a new teacher and add them to the list
      operationId: createTeacher
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateTeacher'
      responses:
        '201':
          description: Successfully created a new Teacher
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Teacher'
    get:
      tags:
        - teachers
      summary: Get all teachers
      description: Get all of the teachers from the list
      operationId: getTeachers
      responses:
        '200':
          description: Successfully return the list of teachers
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AllTeachers'
  /teachers/{id}:
    get:
      tags:
        - teachers
      summary: Get a teacher
      description: Get a teacher by ID
      operationId: getSpecificTeacher
      parameters:
        - name: id
          in: path
          description: The ID of the teacher to get
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Successfully return the teacher specified
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Teacher'
    put:
      tags:
        - teachers
      summary: Update a teacher
      description: Update the teacher with the given id in the list
      operationId: updateTeacher
      parameters:
        - name: id
          in: path
          description: The ID of the teacher to update
          required: true
          schema:
            type: integer
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateTeacher'
      responses:
        '201':
          description: Successfully updated the specified teacher
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Teacher'
    delete:
      tags:
        - teachers
      summary: Delete a teacher
      description: Delete the teacher with the given id from the list and return their details
      operationId: deleteTeacher
      parameters:
        - name: id
          in: path
          description: The ID of the teacher to delete
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Successfully deleted the specified teacher
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Teacher'

components:
  schemas:
    CreateTeacher:
      type: object
      required: [name, location, subject, email]
      properties:
        name:
          type: string
          example: "Dave Ames"
        location:
          type: string
          example: "Lancashire"
        subject:
          type: string
          example: "Java"
        email:
          type: string
          example: "dave@dave.com"
    Teacher:
      type: object
      properties:
        id:
          type: integer
          example: 1
        name:
          type: string
          example: "Dave Ames"
        location:
          type: string
          example: "Lancashire"
        subject:
          type: string
          example: "Java"
        email:
          type: string
          example: "dave@dave.com"
    AllTeachers:
      type: array
      items:
        $ref: '#/components/schemas/Teacher'
