openapi: 3.0.3
info:
  title: Java API MVC, JPA and Hibernate Workshop - Core Criteria
  description: |-
  version: 0.2.2

servers:
  - url: http://localhost:4000
tags:
  - name: teachers
paths:
  /teachers:
    post:
      tags:
        - teachers
      summary: Create a new teacher
      description: Create a new teacher and add them to the list
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateTeacher'
      responses:
        201:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Teacher'
    get:
      tags:
        - teachers
      summary: Get all teachers
      description: Get all of the teachers from the list
      responses:
        200:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AllTeachers'
  /teachers/{id}:
    get:
      tags:
        - teachers
      summary: Get a teacher
      description: Get a teacher by ID
      parameters:
        - name: id
          in: path
          description: The ID of the teacher to get
          required: true
          schema:
            type: long
      responses:
        200:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Teacher'
    put:
      tags:
        - teachers
      summary: Update a teacher
      description: Update the teacher with the given id in the list
      parameters:
        - name: id
          in: path
          description: The ID of the teacher to update
          required: true
          schema:
            type: long
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateTeacher'
      responses:
        201:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Teacher'
    delete:
      tags:
        - teachers
      summary: Delete a teacher
      description: Delete the teacher with the given id from the list and return their details
      parameters:
        - name: id
          in: path
          description: The ID of the teacher to delete
          required: true
          schema:
            type: long
      responses:
        200:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Teacher'

components:
  schemas:
    CreateTeacher:
      type: object
      required: [name, location, subject, email]
      properties:
        name:
          type: string
          example: "Dave Ames"
        location:
          type: string
          example: "Lancashire"
        subject:
          type: string
          example: "Java"
        email:
          type: string
          example: "dave@dave.com"
    Teacher:
      type: object
      properties:
        id:
          type: integer
          example: 1
        name:
          type: string
          example: "Dave Ames"
        location:
          type: string
          example: "Lancashire"
        subject:
          type: string
          example: "Java"
        email:
          type: string
          example: "dave@dave.com"
    AllTeachers:
      type: array
      items:
        $ref: '#/components/schemas/Teacher'
